# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: truelearner
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    HASURA_ENDPOINT: ${env:HASURA_ENDPOINT}
    HASURA_ADMIN_SECRET: ${env:HASURA_ADMIN_SECRET}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
